# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
require 'yaml'
secmachines = YAML.load_file("machines.yml")

Vagrant.configure("2") do |config|
  secmachines.each do |machines|
    config.vm.define machines["name"] do |server|
      server.vm.hostname = machines["name"]
      server.vm.box = machines["box"]
      server.vm.box_check_update = false
      server.vm.network machines["net"], ip: machines["ip"], dns: "8.8.8.8" 
      # machines["ports"].each do |port|
      #   server.vm.network "forwarded_port", guest: port["guest"], host: port["host"]
      # end
      # if machines['disk']['enable']
      #   server.vm.disk :disk, size: machines['disk']['size'], name: "#{machines['name']}#{machines['disk']['desc']}"
      # end
            
      server.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--groups", "/DockerSwarm"]
        vb.memory = machines["memory"]
        vb.cpus = machines["cpus"]
        vb.name = machines["name"]
      end
      server.vm.provision "shell", path: machines["script"]
    end
  end
end
