# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   # #Nome da Imagem que será baixada
   config.vm.box = "debian/bookworm64"
   
   config.vm.box_check_update = false #Verificar o update da vbox
   #config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"   
   config.vm.network "private_network", ip: "192.168.33.11" #Definindo o tipo de rede e um ip para a máquina virtual
   config.vm.synced_folder "files", "/files" #
  
   config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
    
      
      #hd = 'E:\VMS\Vagrant\teste.vdi'
      vb.customize ["modifyvm", :id, "--groups", "/Vagrant"]
      vb.customize ['createhd', '--filename', 'db12hd_sdb', '--size', 10 * 1024]
      vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'db12hd_sdb.vdi']
      
      vb.name = "Db12hd" #Definindo o nome da Máquina
      vb.cpus = 2 #Definindo Quantidade de CPU
      vb.gui = false #Definindo se abrirá ou não a gui do virtualbox
      vb.memory = "2024" #Configurar a memória
   end
   config.vm.provision "shell", inline: <<-SHELL #executando update do Debian durante o provisionamento. 
     hostnamectl set-hostname NextCloud
     apt-get update -y
     
   SHELL
   # config.vm.provision "shell", path:"files/makedb.sh"
end
