# -*- mode: ruby -*-
# vi: set ft=ruby :

machineName="ALMA09"

Vagrant.configure("2") do |config|
   #config.vm.box = "bento/almalinux-9"
   #config.vm.box_version = "202303.13.0" #9.1 bento
   #config.vm.box_version = "202208.18" #9.0 bento
   
   #config.vm.box = "generic/alma9"
   config.vm.box = "almalinux/9"
   #config.vm.box_version = "4.3.4"
   config.vm.box_check_update = false #Verificar o update da vbox
   #config.vm.network "public_network", ip: "10.0.19.156"
   config.vm.network "private_network", ip: "192.168.33.10"
   config.vm.synced_folder "../arq", "/arq"
   config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
      vb.customize ["modifyvm", :id, "--groups", "/Homologacao"]
      vb.name = machineName
      vb.cpus = 2
      vb.gui = false 
      vb.memory = "2024" 
   end
   config.vm.provision "shell", inline: <<-SHELL 
   dnf install epel-release  -y
   dnf update -y
   dnf install netcat net-tools wget perl -y
   hostnamectl set-hostname alma09teste02
   wget -P /opt https://github.com/glpi-project/glpi-agent/releases/download/1.5/glpi-agent-1.5-linux-installer.pl
   perl /opt/glpi-agent-1.5-linux-installer.pl -s "http://glpihmlg.mpes.mp.br" --tag $(hostname -a) --httpd-trust=127.0.0.1/32 --no-ssl-check --distro=CentOS --force --runnow -l /tmp -Q -v
   SHELL
  
end
