# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   config.vm.box = "bento/debian-12" #Nome da Imagem que será baixada
   config.vm.box_check_update = true #Verificar o update da vbox
   config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"  
   config.vm.network "private_network", ip: "192.168.33.10" #Definindo o tipo de rede e um ip para a máquina virtual
   config.vm.synced_folder "files", "/files" #
  
   config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
      vb.name = "Debian-phpIPAM" #Definindo o nome da Máquina
      vb.cpus = 2 #Definindo Quantidade de CPU
      vb.gui = false #Definindo se abrirá ou não a gui do virtualbox
      vb.memory = "1424" #Configurar a memória
   end
   config.vm.provision "shell", inline: <<-SHELL #executando update do Debian durante o provisionamento. 
     apt-get update -y
     apt install apache2 apache2-utils -y 
     a2enmod rewrite ; a2enmod headers
     apt install libapache2-mod-php php php-mysql php-cli php-pear php-gmp php-gd php-bcmath php-mbstring php-curl php-xml php-zip -y
     apt install mariadb-server mariadb-client -y
   SHELL
end
