Vagrant.configure("2") do |config|
  config.vm.box = "isaqueprofeta/zabbix-debian11"
  config.vm.box_version = "6.0"

config.vm.network "forwarded_port", guest: 80, host: 80
   config.vm.network "public_network"
   config.vm.synced_folder ".", "/vagrant" #
  
   config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
      vb.name = "Zabbix-Server6.0" #Definindo o nome da Máquina
      vb.cpus = 2 #Definindo Quantidade de CPU
      vb.gui = false #Definindo se abrirá ou não a gui do virtualbox
      vb.memory = "2024" #Configurar a memória
   end
   config.vm.provision "shell", inline: <<-SHELL #executando update do Debian durante o provisionamento. 
     
   SHELL


end