# -*- mode: ruby -*-
# vi: set ft=ruby :

machineName="ALMA08"

Vagrant.configure("2") do |config|
   config.vm.box = "generic/alma8" # other boxes almalinux/9
   config.vm.box_check_update = false #Verificar o update da vbox
   config.vm.network "forwarded_port", guest: 62364, host: 8888, host_ip: "127.0.0.1"   
   #config.vm.network "public_network", ip: "10.0.19.157"
   config.vm.network "private_network", ip: "192.168.33.13"
   config.vm.synced_folder "../arq", "/arq"
   config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
      vb.customize ["modifyvm", :id, "--groups", "/Homologacao"]
      vb.name = machineName
      vb.cpus = 2
      vb.gui = false 
      vb.memory = "2024" 
   end
   config.vm.provision "shell", inline: <<-SHELL 
     dnf install epel-release  -y
     #dnf update -y
     dnf install netcat net-tools wget -y
     hostnamectl set-hostname Alma08Private04
   SHELL
end
