# -*- mode: ruby -*-
# vi: set ft=ruby :

machineName="FEDORA38"

Vagrant.configure("2") do |config|
  # config.vm.box = "generic/fedora38"
   
  #config.vm.box = "fedora/38-beta-cloud-base"
   #config.vm.box_version = "38.20230307.2"
   config.vm.box = "bento/fedora-38"
  
   config.vm.box_check_update = false #Verificar o update da vbox
   #config.vm.network "public_network", ip: "10.0.19.156"
   config.vm.network "private_network", ip: "192.168.33.10"
   config.vm.synced_folder "../arq", "/arq"
   config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
      vb.customize ["modifyvm", :id, "--groups", "/Homologacao"]
      vb.name = machineName
      vb.cpus = 2
      vb.gui = false 
      vb.memory = "2024" 
   end
   config.vm.provision "shell", inline: <<-SHELL 
     dnf install epel-release  -y
     #dnf update -y
     dnf install netcat net-tools wget perl -y
     source /arq/glpi-install
     hostnamectl set-hostname Fedora38Private02
   SHELL
  
end
