---
- name: Instalar e configurar Apache no Debian 12
  hosts: apache_server
  become: true # Necessário para executar tarefas como root
  tasks:
  - name: Instalando pacotes de manipulacao
    apt:
      name:
      - xz-utils
      - bzip2
      - unzip
      - curl
      state: present

  - name: Instalar dependencias GLPI
    apt:
      name:
      - apache2
      - libapache2-mod-php
      - php-soap
      - php-cas
      - php
      - php-apcu
      - php-cli
      - php-common
      - php-curl
      - php-gd
      - php-imap
      - php-ldap
      - php-mysql
      - php-xmlrpc
      - php-xml
      - php-mbstring
      - php-bcmath
      - php-intl
      - php-zip
      - php-redis
      - php-bz2
      - zip
      state: present

  - name: Copiando arquivo verdanadesk.conf -> conf-available
    template:
      src: etc/apache2/conf-available/verdanadesk.conf
      dest: /etc/apache2/conf-available/verdanadesk.conf

  - name: Clonar repositório Git ignorando validação de certificado SSL
    git:
      repo: https://github.com/verdanatech/glpi.git
      dest: /var/www/verdanadesk/glpi
      version: 10.0.16
      clone: yes
      force: yes

  - name: Movendo Diretorio de segurança
    shell: mv /var/www/verdanadesk/glpi/{{item}} /var/www/verdanadesk/
    with_items:
    - files
    - config

  - name: Criar diretórios necessários
    file:
      path: "/var/www/verdanadesk/files/{{item}}"
      state: directory
      owner: www-data
      group: www-data
      mode: '0755'
    loop:
    - _cache
    - _cron
    - _dumps
    - _graphs
    - _lock
    - _pictures
    - _plugins
    - _rss
    - _sessions
    - _tmp
    - _uploads

  - name: Ajustar permissões Apache
    file:
      path: /var/www/verdanadesk
      owner: www-data
      group: www-data
      mode: '0755'
      recurse: yes

  - name: Movendo Pastas Files e Config
    shell: |
      mv /var/www/verdanadesk/glpi/files /var/www/verdanadesk/
      ln -s /var/www/verdanadesk/files/ /var/www/verdanadesk/glpi/files
      ln -s /var/www/verdanadesk/glpi /var/www/html/glpi
      ln -s /var/www/verdanadesk/config /var/www/html/glpi/config
      mv /var/www/verdanadesk/glpi/config /var/www/verdanadesk/
      mkdir -p /var/www/verdanadesk/glpi/marketplace
      sed -i "s|'GLPI_CONFIG_DIR' *=> *GLPI_ROOT \. '/\.\./\.\./config'|'GLPI_CONFIG_DIR'      => GLPI_ROOT . '/config'|" /var/www/verdanadesk/glpi/inc/based_config.php
      sed -i "s|'GLPI_VAR_DIR' *=> *GLPI_ROOT \. '/\.\./\.\./files'|'GLPI_VAR_DIR' => GLPI_ROOT . '/files'|" /var/www/verdanadesk/glpi/inc/based_config.php

  - name: Ajustar propriedades da aplicacao GLPI
    shell: |
      chown root:root /var/www/verdanadesk/glpi -Rf
      chown www-data:www-data /var/www/verdanadesk/files -Rf
      chown www-data:www-data /var/www/verdanadesk/config -Rf
      chown www-data:www-data /var/www/verdanadesk/glpi/marketplace -Rf
      find /var/www/verdanadesk/ -type d -exec chmod 755 {} \;
      find /var/www/verdanadesk/ -type f -exec chmod 644 {} \;

  - name: Habilitando modulos apache
    shell: |
      sed -i 's/^session.cookie_httponly.*/session.cookie_httponly = on/' /etc/php/8.2/apache2/php.ini
      a2enmod rewrite
      a2enconf verdanadesk.conf
      systemctl reload apache2
  roles:
  - padrao
