---
- name: Playbook para instalar e configurar o MariaDB Server
  hosts: mariadb_server
  become: yes

  vars:
    mariadb_root_password: "P@ssw0rd"
    mariadb_bind_address: "0.0.0.0"
    mariadb_port: 3306
    mariadb_user: "user"
    mariadb_user_password: "P@ssw0rd"

  tasks:
  # Atualizar repositórios e pacotes
  - name: Atualizar pacotes do sistema
    apt:
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: Atualizar pacotes do sistema (RHEL/CentOS)
    yum:
      name: "*"
      state: latest
    when: ansible_facts['os_family'] == "RedHat"

  # Instalar MariaDB Server
  - name: Instalar MariaDB Server no Debian/Ubuntu
    apt:
      name: mariadb-server
      state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: Instalar MariaDB Server no RHEL/CentOS
    yum:
      name: mariadb-server
      state: present
    when: ansible_facts['os_family'] == "RedHat"

  # Habilitar e iniciar o serviço
  - name: Habilitar e iniciar o MariaDB
    service:
      name: mariadb
      state: started
      enabled: yes

  # Configurar senha do root
  # - name: Configurar senha do root do MariaDB
  #   shell: |
  #     mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mariadb_root_password }}';"
  #   args:
  #     executable: /bin/bash
  #Cadastrando usuário do banco
  - name: Criar usuário no MariaDB e garantir privilégios de acesso remoto
    shell: |
      mysql -e "CREATE USER '{{ mariadb_user }}'@'%' IDENTIFIED BY '{{ mariadb_user_password }}';"
      mysql -e "GRANT ALL PRIVILEGES ON *.* TO '{{ mariadb_user }}'@'%' WITH GRANT OPTION;"
      mysql -e "FLUSH PRIVILEGES;"
    args:
      executable: /bin/bash

  # Configurar arquivo de configuração (my.cnf)
  - name: Configurar arquivo my.cnf
    copy:
      dest: /etc/mysql/mariadb.conf.d/50-server.cnf
      content: |
        [mysqld]
        bind-address = {{ mariadb_bind_address }}
        port = {{ mariadb_port }}
    notify:
    - Restart MariaDB
  # Reiniciar o MariaDB (caso necessário)
  handlers:
  - name: Restart MariaDB
    service:
      name: mariadb
      state: restarted
