---
- name: Instalar e configurar Apache no Debian 12
  hosts: apache_server
  become: true # Necessário para executar tarefas como root
  tasks:
  - name: Atualizar lista de pacotes
    apt:
      update_cache: yes

  - name: Instalar Apache
    apt:
      name: apache2
      state: present

  - name: Habilitar e iniciar o serviço Apache
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Configurar página inicial
    copy:
      dest: /var/www/html/index.html
      content: |
        <!DOCTYPE html>
        <html>
        <head>
          <title>Bem-vindo ao Apache</title>
        </head>
        <body>
          <h1>Apache instalado com sucesso no Debian 12!</h1>
        </body>
        </html>
