---
- name: Playbook para instalar e configurar o MariaDB Server
  hosts: mariadb_server
  become: yes
  vars_files:
    - banco.yaml
  tasks:
    - name: Instalar MariaDB Server no Debian/Ubuntu
      apt:
        name:
        - mariadb-server
        - mariadb-client
        - python3-mysqldb
        - python3-dev 
        - default-libmysqlclient-dev 
        - build-essential 
        state: present
    # Criar banco de dados 
    - name: Criando DB
      mysql_db:
        name: "{{dbname}}"
        state: present
    - name: Criar um usuário no MariaDB
      mysql_user:
        name: "{{dbusername}}"
        password: "{{dbpassword}}"
        priv: '*.*:ALL'
        host: "%"
        state: present
      notify:
        - restart_mariadb  
    # Configurar arquivo de configuração (my.cnf)
    - name: Configurar arquivo my.cnf
      copy:
          dest: /etc/mysql/mariadb.conf.d/50-server.cnf
          content: |
            [mysqld]
            bind-address = "{{mariadb_bind_address}}"
            port = "{{ mariadb_port }}"
      notify:
        - restart_mariadb
  
  handlers:
  - name: restart_mariadb
    service:
      name: mariadb
      state: restarted
  roles:
    - padrao


  #   - name: Adicionar usuário ao MariaDB
  #     mysql_user:
  #       name: dba
  #       password: "dba"
  #       priv: "meu_banco.*:ALL"
  #       host: "%"
  #       state: present
  #     #Habilitar e iniciar o serviço
  #   - name: Habilitar e iniciar o MariaDB
  #     service:
  #         name: mariadb
  #         state: started
  #         enabled: yes
  
  # handlers:
  #     - name: Restart MariaDB
  #       service:
  #         name: mariadb
  #         state: restarted
  # roles:
  #   - defaultos
