# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   # #Nome da Imagem que será baixada
   #config.vm.box_version = "0.0.1" #Versão atual bento/debian-12
   #config.vm.box = "generic/debian12"
   #config.vm.box = "bento/debian-12"
   config.vm.box = "debian/bookworm64"
   
   config.vm.box_check_update = false #Verificar o update da vbox
   config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"   
   config.vm.network "private_network", ip: "192.168.33.10" #Definindo o tipo de rede e um ip para a máquina virtual
   config.vm.synced_folder "files", "/files" #
  
   config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
      vb.name = "Debian12Nextcloud" #Definindo o nome da Máquina
      vb.cpus = 2 #Definindo Quantidade de CPU
      vb.gui = false #Definindo se abrirá ou não a gui do virtualbox
      vb.memory = "2024" #Configurar a memória
   end
   config.vm.provision "shell", inline: <<-SHELL #executando update do Debian durante o provisionamento. 
     apt-get update -y
     apt install -y aptitude
     apt install -y apache2
     apt install -y libapache2-mod-php
     apt install -y mariadb-server
     systemctl enable --now apache2 mariadb
 
   SHELL
end
