# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   # #Nome da Imagem que será baixada
   #config.vm.box_version = "0.0.1" #Versão atual bento/debian-12
   #config.vm.box = "generic/debian12"
   #config.vm.box = "bento/debian-12"
   config.vm.box = "debian/bookworm64"
   
   config.vm.box_check_update = false #Verificar o update da vbox
   config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"   
   config.vm.network "private_network", ip: "192.168.33.10" #Definindo o tipo de rede e um ip para a máquina virtual
   config.vm.synced_folder "files", "/files" #
  
   config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
      vb.customize ["modifyvm", :id, "--groups", "/Vagrant"]
      vb.name = "Debian12Nextcloud" #Definindo o nome da Máquina
      vb.cpus = 2 #Definindo Quantidade de CPU
      vb.gui = false #Definindo se abrirá ou não a gui do virtualbox
      vb.memory = "2024" #Configurar a memória
   end
   config.vm.provision "shell", inline: <<-SHELL #executando update do Debian durante o provisionamento. 
     hostnamectl set-hostname DB12-NextCloud
     apt-get update -y
    # apt upgrade -y
     apt install -y aptitude
     apt install -y apache2
     apt install -y php libapache2-mod-php php-mysql php-common php-gd php-xml php-mbstring php-zip php-curl
     apt install -y mariadb-server
     systemctl enable --now apache2 mariadb
     #configuradndo site Next Cloud 
     cp /files/nextcloud.conf /etc/apache2/sites-available/
     ln -s /etc/apache2/sites-available/nextcloud.conf /etc/apache2/sites-enabled/
     cd /files
     if [ -e "latest.tar.bz2" ] ; then
         tar xvf latest.tar.bz2
      else
         wget https://download.nextcloud.com/server/releases/latest.tar.bz2
         tar xvf latest.tar.bz2
      fi 
     mv nextcloud /var/www/html/
     mkdir -p /var/www/html/nextcloud/data
     chown -R www-data:www-data /var/www/html/nextcloud/
     chmod -R 755 /var/www/html/nextcloud/
     a2enmod headers rewrite env dir mime
     systemctl restart apache2 
   SHELL
   config.vm.provision "shell", path:"files/makedb.sh"
end
