# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME="Debian12"

Vagrant.configure("2") do |config|
    #config.vm.box = "debian/bookworm64"
    config.vm.box = "bento/debian-12"
    config.vm.box_check_update = false 

    config.vm.network "public_network", bridge: "default", type: "dhcp"
    config.vm.synced_folder ".", "/vagrant" 
   
    config.vm.provider "virtualbox" do |vb| 
       vb.name = HOSTNAME 
       vb.cpus = 1 
       vb.gui = false 
       vb.memory = "2024" 
       vb.customize ["modifyvm", :id, "--groups", "/Vagrant"]
       
    end
    config.vm.disk :disk, size: "25GB", name: "debian12sdb"
    config.vm.provision "shell", inline: <<-SHELL 
       sudo apt update -y
	   apt install xfsprogs net-tools -y
    SHELL
 end