# -*- mode: ruby -*-
# vi: set ft=ruby :

machineName="DEBIAN12"

Vagrant.configure("2") do |config|
   #config.vm.box = "generic/debian12" 
   config.vm.box = "aphorise/debian12" 
   config.vm.box_check_update = false
   #config.vm.network "forwarded_port", guest: 62364, host: 1234, host_ip: "127.0.0.1"   
   #config.vm.network "public_network", ip: "10.0.19.157"
   config.vm.network "private_network", ip: "192.168.33.13"
   config.vm.synced_folder "../arq", "/arq"
   config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
      vb.customize ["modifyvm", :id, "--groups", "/Homologacao"]
      vb.name = machineName
      vb.cpus = 1
      vb.gui = false 
      vb.memory = "2024" 
   end
   config.vm.provision "shell", inline: <<-SHELL 
     apt update
     apt install wget perl -y     
     hostnamectl set-hostname debian12Priv04
     source /arq/glpi-install-1.0
   SHELL
end
