# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

require 'yaml'
secmachines = YAML.load_file("machines.yml")

Vagrant.configure("2") do |config|
  secmachines.each do |machines|
    config.vm.define machines["name"] do |server|
      server.vm.hostname = machines["name"]
      server.vm.box = machines["box"]
      server.vm.box_check_update = false
      #"Killer E2600 Gigabit Ethernet Controller"
      # server.vm.network machines["network"], bridge: machines["bridge"], ip: machines["ip"], dns: "8.8.8.8" 
      #server.vm.network "forwarded_port", guest: 80, host: 8080, protocol: "tcp"
      server.vm.network machines["network"], bridge: "auto", ip: machines["ip"] #type: "dhcp"
      server.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--groups", "/Swarm"]
        vb.memory = machines["memory"]
        vb.cpus = machines["cpus"]
        vb.name = machines["name"]
      end
      server.vm.provision "shell", path: machines["script"]
    config.vm.synced_folder "comum", "/vagrant", disabled: false   
    config.vm.provision "shell", inline: <<-SHELL
       #Execução de script básico
       apt update -y
       apt install vim net-tools dos2unix -y
       curl -fsSL https://get.docker.com -o get-docker.sh
       sudo sh get-docker.sh
    SHELL

    end
  end
end
