---
- name: Instalar MariaDB Server no Debian/Ubuntu
  apt:
    name:
    - mariadb-server
    - mariadb-client
    - python3-mysqldb
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Criar um banco de dados para o usuário
  mysql_db:
    name: banco
    state: present
- name: Adicionar usuário ao MariaDB
  mysql_user:
    name: dba
    password: "dba"
    priv: "meu_banco.*:ALL"
    host: "%"
    state: present

# - name: Criando o banco de dados
#   shell: |
#     mysql -u root -e "create database glpi"
#     mysql -u root -e "create user dba@localhost identified by 'Mpes123';"
#     mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'dba'@'%' IDENTIFIED BY 'Mpes123';"
