# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   # #Nome da Imagem que será baixada
   config.vm.box = "kalilinux/rolling"
   config.vm.box_version = "2023.4.0"
   #config.vm.box_download_insecure = true
   #config.vm.box_check_update = false #Verificar o update da vbox
   config.vm.network "public_network", bridge: "Killer E2600 Gigabit Ethernet Controller", type: "dhcp" #Definindo o tipo de rede e um ip para a máquina virtual
   config.vm.synced_folder "Files", "/files" #
  
   config.vm.provider "virtualbox" do |vb| #Configuração da máquina virtual que será criada
      vb.customize ["modifyvm", :id, "--groups", "/CyberSecurity"]
	  vb.name = "Kali-Dio" #Definindo o nome da Máquina
      vb.cpus = 1 #Definindo Quantidade de CPU
      vb.gui = false #Definindo se abrirá ou não a gui do virtualbox
      vb.memory = "2024" #Configurar a memória
   end
   config.vm.provision "shell", inline: <<-SHELL #executando update do Debian durante o provisionamento. 
     hostnamectl set-hostname Kali-Dio
   SHELL
   # config.vm.provision "shell", path:"files/makedb.sh"
end

##Comandos para testar 
#xl info
#xl demesg | less
#xl list -> listará as vms

#Limitar uso de recursos da VM0
############## vi /etc/default/grub
#GRUB_CMDLINE_XEN_DEFAULT="dom0_max_vcpus=1 dom0_mem=1014M,max:1024M" Limitando cpu e memória (rodar  grub-mkconfig)