# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME="Mariadb"

Vagrant.configure("2") do |config|
    #config.vm.box = "debian/bookworm64"
    config.vm.box = "bento/debian-12"
    config.vm.box_check_update = false 
    config.vm.network "forwarded_port", guest: 3306, host: 3333
    config.vm.network "public_network", bridge: "default", type: "dhcp"
    config.vm.synced_folder ".", "/vagrant" 
   
    config.vm.provider "virtualbox" do |vb| 
       vb.name = HOSTNAME 
       vb.cpus = 1 
       vb.gui = false 
       vb.memory = "2024" 
       vb.customize ["modifyvm", :id, "--groups", "/Vagrant"]
    end
    config.vm.provision "shell", inline: <<-SHELL 
       sudo apt update -y
       apt install mariadb-server net-tools -y
    SHELL
 end