# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME="GLPI"

Vagrant.configure("2") do |config|
    #config.vm.box = "debian/bookworm64"
    config.vm.box = "bento/debian-12"
    config.vm.box_check_update = false 
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 443, host: 443
    config.vm.network "forwarded_port", guest: 3306, host: 3366
    
    #config.vm.network "public_network", bridge: "default", type: "dhcp"
    config.vm.synced_folder ".", "/vagrant" 
    config.vm.disk :disk, size: "10GB", name: "sdb"
    config.vm.provider "virtualbox" do |vb| 
       vb.name = HOSTNAME 
       vb.cpus = 2
       vb.gui = false 
       vb.memory = "4024" 
       vb.customize ["modifyvm", :id, "--groups", "/Maria"]
    end
    config.vm.provision "shell", inline: <<-SHELL 
      #  sudo apt update -y
      #  apt install mariadb-server net-tools xfsprogs -y
      #  mkfs.xfs /dev/sdb
      #  mkdir /mnt/mariadb_datadir
      #  chown mysql.mysql /mnt/mariadb_datadir
      #  cp -Rfva /var/lib/mysql/* /mnt/mariadb_datadir
      #  echo "/dev/sdb /mnt/mariadb_datadir xfs defauls 0 0" >> /etc/fstab
    SHELL
 end