# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "universalvishwa/windows-10-professional-x64"
  config.vm.box_version = "1.0.0"
  config.vm.box_check_update = false
  config.vm.network "public_network"
  config.vm.synced_folder ".", "c:\vagrant"
  config.vm.provider "virtualbox" do |vb|
       vb.name="W10"
       vb.gui = true
       vb.memory = "8024"
       vb.cpus="6"
   end
  
end
